[build]
  builder = "dockerfile"
  dockerfilePath = "kds/Dockerfile"
  contextPath = "../"

[deploy]
  healthcheckPath = "/health"
  healthcheckTimeout = 30
  restartPolicyType = "on_failure"
  restartPolicyMaxRetries = 3
