import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
/**
 * CartDrawer — Phase 4a stub.
 * Renders the cart summary. Checkout flow (Phase 4b) wires in
 * guest info collection + POST /v1/online-orders + Stripe CheckoutDrawer.
 */
export function CartDrawer({ cart, onClose, onUpdateQty, onRemove: _onRemove }) {
    return (_jsx("div", { style: { position: 'fixed', inset: 0, zIndex: 50, display: 'flex', justifyContent: 'flex-end', background: 'rgba(0,0,0,0.6)' }, onClick: onClose, children: _jsxs("div", { style: { width: '400px', maxWidth: '100vw', background: 'var(--bg-card)', padding: '24px', height: '100dvh', overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: '16px' }, onClick: (e) => e.stopPropagation(), children: [_jsxs("div", { style: { display: 'flex', justifyContent: 'space-between', alignItems: 'center' }, children: [_jsx("h2", { style: { margin: 0, fontSize: '18px', fontWeight: 700 }, children: "Your cart" }), _jsx("button", { onClick: onClose, style: { background: 'none', border: 'none', color: 'var(--text-muted)', fontSize: '20px', cursor: 'pointer' }, children: "\u00D7" })] }), cart.items.length === 0 && (_jsx("p", { style: { color: 'var(--text-muted)', textAlign: 'center', paddingTop: '40px' }, children: "Your cart is empty." })), cart.items.map((item) => (_jsxs("div", { style: { display: 'flex', gap: '12px', alignItems: 'flex-start', paddingBottom: '14px', borderBottom: '1px solid var(--border)' }, children: [_jsxs("div", { style: { flex: 1 }, children: [_jsx("div", { style: { fontWeight: 600, fontSize: '14px' }, children: item.name }), item.modifiers.length > 0 && (_jsx("div", { style: { fontSize: '12px', color: 'var(--text-muted)', marginTop: '2px' }, children: item.modifiers.map((m) => m.name).join(', ') })), item.notes && (_jsx("div", { style: { fontSize: '12px', color: 'var(--amber)', marginTop: '2px', fontStyle: 'italic' }, children: item.notes })), _jsxs("div", { style: { fontSize: '13px', fontWeight: 600, marginTop: '4px' }, children: ["$", (item.unit_price / 100).toFixed(2)] })] }), _jsxs("div", { style: { display: 'flex', alignItems: 'center', gap: '8px', flexShrink: 0 }, children: [_jsx("button", { onClick: () => onUpdateQty(item.id, item.quantity - 1), style: stepBtn, children: "-" }), _jsx("span", { style: { fontSize: '14px', fontWeight: 600, minWidth: '16px', textAlign: 'center' }, children: item.quantity }), _jsx("button", { onClick: () => onUpdateQty(item.id, item.quantity + 1), style: stepBtn, children: "+" })] })] }, item.id))), cart.items.length > 0 && (_jsxs(_Fragment, { children: [_jsxs("div", { style: { display: 'flex', justifyContent: 'space-between', fontWeight: 700, fontSize: '16px', paddingTop: '4px' }, children: [_jsx("span", { children: "Total" }), _jsxs("span", { children: ["$", (cart.total / 100).toFixed(2)] })] }), _jsx("button", { style: { padding: '14px', borderRadius: 'var(--radius-sm)', border: 'none', background: 'var(--accent)', color: '#fff', fontWeight: 700, fontSize: '15px', cursor: 'pointer' }, onClick: () => alert('Checkout coming in Phase 4b!'), children: "Proceed to checkout" })] }))] }) }));
}
const stepBtn = {
    width: '28px', height: '28px', borderRadius: '6px',
    border: '1px solid var(--border)', background: 'var(--bg-elevated)',
    color: 'var(--text)', fontWeight: 700, fontSize: '16px',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    cursor: 'pointer',
};
