import { ThemeConfig } from './types';

export const THEME_PRESETS: Record<string, ThemeConfig> = {
  'classic-light': {
    id: 'classic-light',
    name: 'Classic Bistro (Light)',
    mode: 'light',
    radius: 'lg',
    font: 'inter',
    animation: 'normal',
    colors: {
      primary: '#0f172a',
      primaryForeground: '#ffffff',
      background: '#f8f9fa',
      foreground: '#0f172a',
      card: '#ffffff',
      cardForeground: '#0f172a',
      popover: '#ffffff',
      popoverForeground: '#0f172a',
      secondary: '#f1f5f9',
      secondaryForeground: '#0f172a',
      muted: '#f1f5f9',
      mutedForeground: '#64748b',
      accent: '#f1f5f9',
      accentForeground: '#0f172a',
      destructive: '#ef4444',
      destructiveForeground: '#ffffff',
      border: '#e2e8f0',
      input: '#e2e8f0',
      ring: '#0f172a',
      success: '#10b981',
      warning: '#f59e0b',
      cosBg: '#f8f9fa',
      cosSurface: '#ffffff',
      cosSurface2: '#f1f3f5',
      cosBorder: '#e5e7eb',
      cosText: '#1f2937',
      cosBrand: '#0f172a',
    },
  },

  'midnight-dark': {
    id: 'midnight-dark',
    name: 'Midnight Slate (Dark)',
    mode: 'dark',
    radius: 'lg',
    font: 'inter',
    animation: 'normal',
    colors: {
      primary: '#f8fafc',
      primaryForeground: '#0f172a',
      background: '#090d16',
      foreground: '#f8fafc',
      card: '#0f172a',
      cardForeground: '#f8fafc',
      popover: '#0f172a',
      popoverForeground: '#f8fafc',
      secondary: '#1e293b',
      secondaryForeground: '#f8fafc',
      muted: '#1e293b',
      mutedForeground: '#94a3b8',
      accent: '#1e293b',
      accentForeground: '#f8fafc',
      destructive: '#f43f5e',
      destructiveForeground: '#ffffff',
      border: '#1e293b',
      input: '#1e293b',
      ring: '#38bdf8',
      success: '#10b981',
      warning: '#fbbf24',
      cosBg: '#090d16',
      cosSurface: '#0f172a',
      cosSurface2: '#1e293b',
      cosBorder: '#334155',
      cosText: '#f8fafc',
      cosBrand: '#38bdf8',
    },
  },

  'kitchen-oled': {
    id: 'kitchen-oled',
    name: 'Kitchen OLED High-Contrast',
    mode: 'oled',
    radius: 'sm',
    font: 'mono',
    animation: 'instant',
    colors: {
      primary: '#fbbf24',
      primaryForeground: '#000000',
      background: '#000000',
      foreground: '#ffffff',
      card: '#080808',
      cardForeground: '#ffffff',
      popover: '#080808',
      popoverForeground: '#ffffff',
      secondary: '#171717',
      secondaryForeground: '#ffffff',
      muted: '#171717',
      mutedForeground: '#a3a3a3',
      accent: '#262626',
      accentForeground: '#fbbf24',
      destructive: '#ff0033',
      destructiveForeground: '#ffffff',
      border: '#333333',
      input: '#262626',
      ring: '#fbbf24',
      success: '#00ff66',
      warning: '#ffcc00',
      cosBg: '#000000',
      cosSurface: '#0a0a0a',
      cosSurface2: '#141414',
      cosBorder: '#404040',
      cosText: '#ffffff',
      cosBrand: '#fbbf24',
    },
  },

  'cyberpunk-neon': {
    id: 'cyberpunk-neon',
    name: 'Cyberpunk Neon',
    mode: 'dark',
    radius: 'sm',
    font: 'mono',
    animation: 'playful',
    colors: {
      primary: '#06b6d4',
      primaryForeground: '#000000',
      background: '#050510',
      foreground: '#e0f2fe',
      card: '#0b0f19',
      cardForeground: '#e0f2fe',
      popover: '#0b0f19',
      popoverForeground: '#e0f2fe',
      secondary: '#1e1b4b',
      secondaryForeground: '#38bdf8',
      muted: '#1e1b4b',
      mutedForeground: '#818cf8',
      accent: '#ec4899',
      accentForeground: '#ffffff',
      destructive: '#f43f5e',
      destructiveForeground: '#ffffff',
      border: '#312e81',
      input: '#1e1b4b',
      ring: '#06b6d4',
      success: '#10b981',
      warning: '#f59e0b',
      cosBg: '#050510',
      cosSurface: '#0b0f19',
      cosSurface2: '#1e1b4b',
      cosBorder: '#312e81',
      cosText: '#e0f2fe',
      cosBrand: '#06b6d4',
    },
  },

  'emerald-botanical': {
    id: 'emerald-botanical',
    name: 'Botanical Garden (Emerald)',
    mode: 'light',
    radius: 'xl',
    font: 'inter',
    animation: 'normal',
    colors: {
      primary: '#047857',
      primaryForeground: '#ffffff',
      background: '#f4fbf7',
      foreground: '#064e3b',
      card: '#ffffff',
      cardForeground: '#064e3b',
      popover: '#ffffff',
      popoverForeground: '#064e3b',
      secondary: '#e6f4ed',
      secondaryForeground: '#047857',
      muted: '#e6f4ed',
      mutedForeground: '#059669',
      accent: '#d1fae5',
      accentForeground: '#065f46',
      destructive: '#e11d48',
      destructiveForeground: '#ffffff',
      border: '#a7f3d0',
      input: '#d1fae5',
      ring: '#047857',
      success: '#10b981',
      warning: '#d97706',
      cosBg: '#f4fbf7',
      cosSurface: '#ffffff',
      cosSurface2: '#e6f4ed',
      cosBorder: '#a7f3d0',
      cosText: '#064e3b',
      cosBrand: '#047857',
    },
  },

  'bordeaux-wine': {
    id: 'bordeaux-wine',
    name: 'Bordeaux & Wine',
    mode: 'dark',
    radius: 'lg',
    font: 'serif',
    animation: 'normal',
    colors: {
      primary: '#e11d48',
      primaryForeground: '#ffffff',
      background: '#120b0e',
      foreground: '#fdf2f4',
      card: '#1e1015',
      cardForeground: '#fdf2f4',
      popover: '#1e1015',
      popoverForeground: '#fdf2f4',
      secondary: '#2e121b',
      secondaryForeground: '#f43f5e',
      muted: '#2e121b',
      mutedForeground: '#fda4af',
      accent: '#4c0519',
      accentForeground: '#ffe4e6',
      destructive: '#f43f5e',
      destructiveForeground: '#ffffff',
      border: '#4c0519',
      input: '#2e121b',
      ring: '#e11d48',
      success: '#10b981',
      warning: '#f59e0b',
      cosBg: '#120b0e',
      cosSurface: '#1e1015',
      cosSurface2: '#2e121b',
      cosBorder: '#4c0519',
      cosText: '#fdf2f4',
      cosBrand: '#e11d48',
    },
  },
};

export const DEFAULT_THEME: ThemeConfig = THEME_PRESETS['classic-light']!;
